### ISSUE TITLE
Create to-do endpoints

### ISSUE THREAD

**Issue by miguel5g** [miguel5g/todo-app#25]
The endpoints will be

- [ ] `POST /api/todos`
- [ ] `GET /api/todos`
- [ ] `GET /api/todos/:id`
- [ ] `PATCH /api/todos/:id`
- [ ] `DELETE /api/todos/:id`

_this requires issue #23 to be done first_
